name: Deploy to Firebase Hosting on merge
on:
  pull_request:
    branches: [ main ]
    types: [closed]
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 📁
        uses: actions/checkout@v1
      - name: installing 📦
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: yarn install
        run: yarn install
      - name: testing 🔬
        run: yarn test plants.test.js
        run: yarn test math.test.js
        run: yarn test sale.test.js
      - name: eslint 🔎
        uses: icrawl/action-eslint@v1
        with:
          custom-glob: src/**
      - name: Prettify 🔪
        uses: actionsx/prettier@v2
        with:
         args: --check .
  final_deploy:
          if: github.event.pull_request.merged == true
          runs-on: ubuntu-latest
          needs: [build]
          steps:
              - name: Checkout 📁
                uses: actions/checkout@v2
              - name: Final deploy 🔥🚀
                uses: FirebaseExtended/action-hosting-deploy@v0
                with:
                  repoToken: '${{ secrets.GITHUB_TOKEN }}'
                  firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_QATARPLANTS_5A735 }}'
                  channelId: live
                  projectId: qatarplants-5a735
          
