name: nitly
'on':
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 📁
        uses: actions/checkout@v1
      - name: installing 📦
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: yarn install
        run: yarn install
      - name: testing 🔬
        run: yarn test plants.test.js
      - name: eslint 🔎
        uses: icrawl/action-eslint@v1
        with:
          custom-glob: src/**
      - name: Prettify 🔪
        uses: actionsx/prettier@v2
        with:
         args: --check .
  netify_deploy:
      runs-on: ubuntu-latest
      needs: [build]
      steps:
        - name: Checkout 📁
          uses: actions/checkout@v1
        - name: Netify deploy 💠🚀
          uses: nwtgck/actions-netlify@v1.2
          with:
            publish-dir: './src'
            production-branch: main
            deploy-message: '${{ github.event.head_commit.message }}'
          env:
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
