on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v1
      - name: installing 
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: testing
        run: yarn test
      - name: yarn install
        run: yarn install
      - name: eslint 
        uses: icrawl/action-eslint@v1
        with:
          custom-glob: src/**
      - name: Prettify 
        uses: actionsx/prettier@v2
        with:
         args: --check .

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "amna ikram"
          heroku_email: "amna_2023@hotmail.com"
