on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v1
      - name: installing 
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: yarn install
        run: yarn install
      - name: testing
        run: npm test plants.test.js
      - name: eslint 
        uses: icrawl/action-eslint@v1
        with:
          custom-glob: src/**
      - name: Prettify 
        uses: actionsx/prettier@v2
        with:
         args: --check .
  deploy:
   name: Deploy to Firebase 🔥🚀
   runs-on: ubuntu-latest
   needs: [build]
   steps:
      - uses: actions/checkout@v2
      - uses: lowply/deploy-firebase@v0.0.5
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: "Qatar plants"
          projectId: "qatar-plants-1eb4c"
